app.cors.allowed-origins=http://localhost:4200

spring.datasource.url=jdbc:mysql://localhost:3306/operations_board?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=fe8b4f84

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#db as usual
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.defer-datasource-initialization=false
#spring.sql.init.mode=never

#db reseed
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always