spring.application.name=operationsboard

server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:operations_board}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:fe8b4f84}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

spring.sql.init.mode=always
spring.sql.init.continue-on-error=false

spring.jackson.time-zone=UTC

logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=INFO